# Generated by Django 5.1.1 on 2024-10-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_blog_post_author__038a48_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_author__038a48_idx',
        ),
    ]
