# Generated by Django 5.1.1 on 2024-10-10 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_blog_commen_post_id_5fee65_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_author__038a48_idx',
        ),
    ]
