# Generated by Django 5.1.1 on 2024-10-10 07:39

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_blog_post_author__038a48_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_author__038a48_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.HashIndex(fields=['author'], name='blog_post_author__2df847_hash'),
        ),
    ]
